// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvUNIR9FSMtQamppeWslSNzWCdMhzM-Hs',
    appId: '1:749003619621:android:1606c26decf624c660eecc',
    messagingSenderId: '749003619621',
    projectId: 'spotify-c97ea',
    storageBucket: 'spotify-c97ea.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdlEAISjlDIh1GSns8BPkJhLYIa5tocj0',
    appId: '1:749003619621:web:00bb534050bd609e60eecc',
    messagingSenderId: '749003619621',
    projectId: 'spotify-c97ea',
    authDomain: 'spotify-c97ea.firebaseapp.com',
    storageBucket: 'spotify-c97ea.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5MYaugd2C2P0Jw_W_IwPGrbwiT-9VUGw',
    appId: '1:749003619621:ios:7cc1c16d59e01cf060eecc',
    messagingSenderId: '749003619621',
    projectId: 'spotify-c97ea',
    storageBucket: 'spotify-c97ea.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5MYaugd2C2P0Jw_W_IwPGrbwiT-9VUGw',
    appId: '1:749003619621:ios:7cc1c16d59e01cf060eecc',
    messagingSenderId: '749003619621',
    projectId: 'spotify-c97ea',
    storageBucket: 'spotify-c97ea.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdlEAISjlDIh1GSns8BPkJhLYIa5tocj0',
    appId: '1:749003619621:web:0a227e7c00c94e1460eecc',
    messagingSenderId: '749003619621',
    projectId: 'spotify-c97ea',
    authDomain: 'spotify-c97ea.firebaseapp.com',
    storageBucket: 'spotify-c97ea.appspot.com',
  );

}